### PR TITLE
Navigation feature added for navigate the web.

### PR DESCRIPTION
**Pull request by SAZZAD1Q2**
Made as when the user clicks on a navbar button the selected section will appear.
Added contact form.

Screenshot 2023-04-01 at 23-12-43 Request #293622 How would you rate the support you received - sazzad1q2@gmail com - Gmail

### CODE REVIEW

**Review by muneebulrehman — COMMENTED** [review]
Hi @SAZZAD1Q2 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is a pair programming project but doesn't have any commit history from your partner. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by Yerimah — CHANGES_REQUESTED** [review]
# STATUS: INVALID 📛 

Hi @SAZZAD1Q2, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is a pair programming activity and requires contribution from your partner.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by abdulhamiid — CHANGES_REQUESTED** [review]
Hi @SAZZAD1Q2 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌ ❌ ❌ 

💡💡 [REQUIRED]

- [ ] This milestone is a [pair-programming](https://github.com/microverseinc/curriculum-javascript/blob/main/books/m4_full_website_v1_1.md#work-and-submission-mode) activity.

- [ ] Please kindly ensure that everyone in your pair programming group has contributed code to the project you're reviewing.

- [ ]  Kindly ensure that your partner's contribution reflects in the commit history. then your project will be reviewed. 👍 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by Deepakdanger — APPROVED** [review]
Hi @SAZZAD1Q2 , 

### Status: Approved ✔️

Your project is complete!  There is nothing else to say other than... it's time to merge it  🚢 
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
